name: .NET PR

on:
  pull_request:
    branches: [ master, main ]
    paths-ignore:
    - '**.md'
    - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Nuget Versions
      run: dotnet build ./tools/Explicit.NuGet.Versions/Explicit.NuGet.Versions.sln
    - name: Build Release
      run: dotnet build Castle.Windsor.sln -c Release
    - name: Castle.Windsor.Tests
      run: dotnet test src/Castle.Windsor.Tests
    - name: Castle.Windsor.Extensions.DependencyInjection.Tests
      run: dotnet test src/Castle.Windsor.Extensions.DependencyInjection.Tests
    - name: Castle.Facilities.AspNetCore.Tests
      run: dotnet test src/Castle.Facilities.AspNetCore.Tests
